### ISSUE TITLE
Appveyor does not work

### ISSUE THREAD

**Issue by opoudjis** [metanorma/itubib#4]
Fails on puppeteer install

**Comment by CAMOBAP795** [comment]
Interesting observation: on windows this issue happens only for ruby 2.3 & 2.4. 2.5 is green for 2 consecutive runs

**Comment by opoudjis** [comment]
@CAMOBAP795 Note that this gem is under development by @andrew2net, and I barely understand the VCR gem he uses for his testing; queries are best addressed to him. 

@andrew2net, @CAMOBAP795 is introducing Windows testing for all gems, and this gem is currently crashing on:

````
 1) ItuBib return string of hit
328     Failure/Error: resp = Net::HTTP.get_response(uri)#.encode("UTF-8")
329
330     VCR::Errors::UnhandledHTTPRequestError:
331
332
333       ================================================================================
334       An HTTP request has been made that VCR does not know how to handle:
335         GET https://www.itu.int/net4/ITU-T/search/api/redirection?dest=http://handle.itu.int/11.1002/1000/13697-en&page=1&position=4
336
337       VCR is currently using the following cassette:
338         - C:/projects/itubib/spec/vcr_cassettes/hits.yml
339           - :record => :once
340           - :match_requests_on => [:method, :uri]
341
342       Under the current configuration VCR can not find a suitable HTTP interaction
343       to replay and is prevented from recording new requests. There are a few ways
344       you can deal with this:
345
346         * If you're surprised VCR is raising this error
347           and want insight about how VCR attempted to handle the request,
348           you can use the debug_logger configuration option to log more details [1].
349         * You can use the :new_episodes record mode to allow VCR to
350           record this new request to the existing cassette [2].
351         * If you want VCR to ignore this request (and others like it), you can
352           set an `ignore_request` callback [3].
353         * The current record mode (:once) does not allow new requests to be recorded
354           to a previously recorded cassette. You can delete the cassette file and re-run
355           your tests to allow the cassette to be recorded with this request [4].
356         * The cassette contains an HTTP interaction that matches this request,
357           but it has already been played back. If you wish to allow a single HTTP
358           interaction to be played back multiple times, set the `:allow_playback_repeats`
359           cassette option [5].
360         * The cassette contains 23 HTTP interactions that have not been
361           played back. If your request is non-deterministic, you may need to
362           change your :match_requests_on cassette option to be more lenient
363           or use a custom request matcher to allow it to match [6].
364
365       [1] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/debug-logging
366       [2] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/record-modes/new-episodes
367       [3] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/ignore-request
368       [4] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/record-modes/once
369       [5] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/request-matching/playback-repeats
370       [6] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/request-matching
371       ================================================================================
372     # ./lib/itubib/scrapper.rb:118:in `get_page'
373     # ./lib/itubib/scrapper.rb:53:in `parse_page'
374     # ./lib/itubib/hit.rb:22:in `fetch'
375     # ./lib/itubib/workers_pool.rb:18:in `block (2 levels) in worker'
376
377
````

**Comment by skalee** [comment]
@opoudjis VCR is a testing gem which records HTTP requests, and then replays them in subsequent test runs. The benefit is that HTTP responses in tests are always the same, no matter of internet connection quality, remote server availability, data changes on remote site, etc. Even headers will be the same, including date-related ones.

VCR is configured in `once` record mode ([docs](https://relishapp.com/vcr/vcr/v/3-0-3/docs/record-modes/once)) which is a default one. Above error means that gem attempted to make some different request than it was doing so far in this particular test.

**Comment by opoudjis** [comment]
@CAMOBAP795 

The errors in itubib, now that Andrej has made the HTML source files local, are UTF-8 errors: the Windows version is treating the raw UTF-8 as bytes. I've had to inject

````
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
````

into the Gemfile to get @andrew2net's specs to work. Presumably @CAMOBAP795 you will have to either do something like that, or make the spec code more overt about UTF-8.

**Comment by CAMOBAP795** [comment]
Ready for review

**Comment by ronaldtse** [comment]
#6 is merged, closing this.
